### ISSUE TITLE
мне шавурму не доставили

### ISSUE THREAD

**Issue by Questern** [Solyaris/Delivery_Food#1]
ну название говорит само за себя я шавурму заказал мне не доставили разработчкику желаю исправить проблему пока 1 звезда

**Comment by Questern** [comment]
шавурма была доставлена разработчкику спасибо проблема была исправлена оператинво ставлю оценку 5 звезд

**Comment by Solyaris** [comment]
Спасибо вам за ваш отзыв! Шавурма правда вкусная
